(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Carrots_atlas_1", frames: [[0,0,1682,1372]]},
		{name:"Carrots_atlas_2", frames: [[0,0,1651,1270]]},
		{name:"Carrots_atlas_3", frames: [[0,0,968,1794],[970,0,635,1673]]},
		{name:"Carrots_atlas_4", frames: [[0,1904,13,14],[0,1796,411,106],[0,1021,569,773],[571,1021,405,743],[571,1766,243,279],[0,0,812,1019]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_3 = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.baxkground = function() {
	this.initialize(img.baxkground);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,6000,4200);


(lib.bookshelf = function() {
	this.initialize(img.bookshelf);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1748,2500);


(lib.bunny = function() {
	this.initialize(ss["Carrots_atlas_3"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.flower = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.flower2 = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.frame = function() {
	this.initialize(ss["Carrots_atlas_4"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.lamp = function() {
	this.initialize(ss["Carrots_atlas_3"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Layer1 = function() {
	this.initialize(ss["Carrots_atlas_2"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.rug = function() {
	this.initialize(img.rug);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2197,790);


(lib.window = function() {
	this.initialize(ss["Carrots_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AiBEhQhJgLg2gfQg0gdgZgoQgNgYgEgZQgEgbAIgYQANgmAxglQA9gvBBgdQAPAYARANQAKAIAXALQAXALAQADQAXADASgIQAHgDABgGQABgEgDgDQgDgDgEgBIgQAAQgOAAgYgLQgegOgLgLQgIgIgIgOIAIgDQgGgDgEgEQgIgGgBgPIABgFIgHACIgCgIQgFgXAOgXQALgTAWgPQAxghA6AEQAaACAQAKQAWANAJAaQADAMACAPQACgCADAAIAAAAQgBAlAEAnIABACIgBAAQgGgCgDgIIAAgCQgBAJABAGQACAJAGAGQAHAGAIgCQALgCAEgPIABgEQABgFAAgHIAAgFQBSAVBPA4QAqAdASAbQAJANABAKIgDADQgIAMgBAFQgFAOAIAbIAFAMQAAALgCAHQgEALgNAOQhKBOhnAcQg6AQhZACIgVAAQhAAAgygIgACMDBQgDACAAAFQAAAEACAEQAEAFAKADQAMADAPAAQAlACAmgOQAYgJAPgPQAGgGAKgOIAIgLQANgSADgLQACgHgBgDQgBgGgFgCIAGgLQACgEgBgDQgBgFgHACQgDABgEAFQgSARgUAJIgUAIIgNAEQgfAJgWgHQgLgDgIgGIgEgEIgCgGQgDgHgIgBQgJAAgEAHQgCAGABAHQAEAMATAMQANAHAIADQAQAGAbgDQARgCAIgDQAHgCAHgEIAMgGQAKgFAIgGIgFAGIgLAOQgIAJgKAGQggAWg6ACIgbAAIgEgBQgFAAgDADgADEAbIgMABQgIACgCAFQgBACAAAHIAAAMIABAIQACAEAGACQAMAFAIABQAMAAAEgKQACgEgBgHQAAgMgCgJQgBgEgDgCQgCgCgFAAIgIgBQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAgAgvi+QgGABgKAIQgPAMgEAOQgCAGAAAJQgBANACAIIAHAPQAOAaAOAFIATAEIAXAHQAKABAJAAQANAAAFgFQADgEAAgFQABgFgEgEQgEgFgQgBQgKAAgcgHQgKgDgEgDQgEgDgGgKIgFgNQgDgMAGgJQAEgGAGgEQAIgEAPAAIAPABIALAFQAQAJAKALQAFAFACAFQAEAIACAAQAEABACgFQADgEABgGQAAgEgFgJQgEgIgFgGQgHgJgPgJQgJgGgFgCQgGgDgbgBQgPAAgEABgAB7iEQgBgXgEgZQgDgTgEgKQgFgJgMgPQgQgSgKgGQgHgFgRgFQgdgIgdABIALgIIAOgJQAQgHAdADQAUADAPAGIARAIQAfARAOAYQALARAEAZQAIApgSAVIgIAKIgbgJg");
	this.shape.setTransform(14.2333,1.73);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAUFbIgngHQg/gNgtgYQhOgogdhEQgOgigBgmQgKABgLgBQgagDgagPQgagPgLgWQgPgcAKgqQAFgXAKgTQAIgPAOgVIAXgjQAbgrgCgjQgBgkgdgiQgKgLgKgIQgjgdgsgHQgUgDgMAFQgIADgEAHQgFAHAAAIQACAMAPAKIANAHQAHAEAFAEQAFAFACAIQACAHgDAGQgHALgPgDQgIgCgOgIQgUgLgQgCQgVgEgPAMQgUAQAEAhQACAQAFAKQAOAbAjAIQAWAFAngEQAOgCAFADQAIAFgBAKQgBAKgIAGQgKAHgZAAQggAAgTgDQgbgFgSgOQgLgKgJgNQgOgWgFgaQgEgcAJgXQAJgZAXgQQAYgQAZAEQgFgPAGgQQAFgPAMgLQAXgUAlADQAaACAhARQA5AdAcAtQAPAZAFAcQAFAdgIAbQgGAUgQAZIgdAqQgPAYgLAZQgOAfADAXQAEAaAZATQAUAOAeAEIAOACQAEgYAKgSQALgUAcgYQBOhEBUglQgDgJgCgIQgEgXAGgWQAKgmApgeQAkgaAtgIIAKgBIABgCIACgGQACgDACgCIAJgGIANgIIANgJQAOgHAdgBIAZAAIATAEQAxANAdAkQAMAOAFAOIAGAQIAFAVQADARgBAMQAAAmgPAWQB8A2AxBLIANASIAAABIADgBQAOgGAPAFQAPAEAIANQAIAMABAWQABARgEALQgCAIgKARQgHALgFADQgEACgGAAIgMALIgVAZQgqAxg8AjQg2AehAAQIgGACQhAAQhKAAQg8AAhBgLgAiOAUQgxAlgNAmQgIAYAEAbQAEAZANAYQAZAoA0AdQA2AfBIALQA6AJBOgBQBZgCA6gQQBngcBKhOQANgOAEgLQACgHAAgLIgFgMQgIgbAFgOQABgFAIgMIADgDQgBgKgJgNQgSgbgqgdQhPg4hSgVIAAAFQAAAHgBAFIgBAEQgEAPgLACQgIACgHgGQgGgGgCgJQgBgGABgJIAAACQADAIAGACIABAAIgBgCQgEgnABglIAAAAQgDAAgCACQgCgPgDgMQgJgagWgNQgQgKgagCQg7gEgxAhQgWAPgLATQgNAXAFAXIACAIIAGgCIgBAFQABAPAIAGQAEAEAGADIgIADQAIAOAIAIQALALAeAOQAYALAOAAIAQAAQAEABADADQADADgBAEQgBAFgHADQgSAJgXgEQgQgDgXgKQgXgLgKgIQgQgNgPgYQhBAdg9AvgAC6j6QARAFAHAFQAKAGAQASQAMAPAFAJQAEAKADATQAEAZABAXIAbAJIAIgKQASgVgIgpQgEgZgLgRQgOgYgfgRIgRgIQgPgGgUgDQgdgDgQAHIgPAJIgLAIIAJAAQAZAAAZAHgAFCDsQgPAAgMgDQgKgDgEgFQgCgEAAgEQAAgFADgCQAEgDAIABIAbAAQA6gCAggWQAKgGAIgJIALgOIAFgGQgIAGgKAFIgMAGQgHAEgHACQgIADgRACQgbADgQgGQgIgDgNgHQgTgMgEgMQgBgHACgGQAEgHAJAAQAIABADAHIACAGIAEAEQAIAGALADQAWAHAfgJIANgEIAUgIQAUgJASgRQAEgFADgBQAHgCABAFQABADgCAEIgGALQAFACABAGQABADgCAHQgDALgNASIgIALQgKAOgGAGQgPAPgYAJQgiAMgiAAIgHAAgAFEBXQgGgCgCgEIgBgIIAAgMQAAgHABgCQACgFAIgCIAMgBQABAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAIABQAFAAACACQADACABAEQACAJAAAMQABAHgCAEQgEAKgMAAQgIgBgMgFgACHgtIgXgHIgTgEQgOgFgOgaIgHgPQgCgIABgNQAAgJACgGQAEgOAPgMQAKgIAGgBQAEgBAPAAQAbABAHADQAFACAJAGQAPAJAHAJQAFAGAEAIQAFAJAAAEQgBAGgDAEQgCAFgEgBQgCAAgEgIQgCgFgFgFQgKgLgQgJIgMgFIgPgBQgPAAgIAEQgGAEgEAGQgGAJADAMIAFANQAGAKAEADQAEADAKADQAdAHAKAAQAQABAEAFQAEAEgBAFQAAAFgDAEQgFAFgNAAIgFAAIgPgBg");
	this.shape_1.setTransform(0.046,0.0247);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.9,-35.7,115.9,71.5);


(lib.Tween8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAUFbQg5gIgtgQQgYgJgVgLQhOgogdhEQgOgigBgmQgKABgLgBQgagDgagPQgagPgLgWQgPgcAKgqQAFgXAKgTQAIgPAOgVIAXgjQAbgrgCgjQgBgkgdgiQgKgLgKgIQgXgSgagKQgPgFgPgDQgUgDgMAFQgIADgEAHQgFAHAAAIQACAMAPAKIANAHQAHAEAFAEQAFAFACAIQACAHgDAGQgHALgPgDQgIgCgOgIQgUgLgQgCQgVgEgPAMQgUAQAEAhQACAQAFAKQAOAbAjAIQAWAFAngEQAOgCAFADQAIAFgBAKQgBAKgIAGQgKAHgZAAQggAAgTgDQgbgFgSgOQgLgKgJgNQgOgWgFgaQgEgcAJgXQAJgZAXgQQAYgQAZAEQgFgPAGgQQAFgPAMgLQAXgUAlADQAQABATAHQAMAEAMAHQA5AdAcAtQAPAZAFAcQAFAdgIAbQgGAUgQAZIgdAqQgPAYgLAZQgOAfADAXQAEAaAZATQAUAOAeAEIAOACQAEgYAKgSQALgUAcgYQBOhEBUglQgDgJgCgIQgEgXAGgWQAKgmApgeQAkgaAtgIIAKgBIABgCIACgGQACgDACgCIAJgGIANgIIANgJQAOgHAdgBIAZAAIATAEQAxANAdAkQAMAOAFAOIAGAQIAFAVQADARgBAMQAAAmgPAWQB8A2AxBLIANASIAAABIADgBQAOgGAPAFQAPAEAIANQAIAMABAWQABARgEALQgCAIgKARQgHALgFADQgEACgGAAIgMALIgVAZQgqAxg8AjQgeAQggANQgeALggAIQhAAQhKAAQg8AAhBgLgAiOAUQgxAlgNAmQgIAYAEAbQAEAZANAYQAZAoA0AdQA2AfBIALQA6AJBOgBQBZgCA6gQQBngcBKhOQANgOAEgLQACgHAAgLIgFgMQgIgbAFgOQABgFAIgMIADgDQgBgKgJgNQgSgbgqgdQhPg4hSgVIAAAFQAAAHgBAFIgBAEQgEAPgLACQgIACgHgGQgGgGgCgJQgBgGABgJIAAACQADAIAGACIABAAIgBgCQgEgnABglIAAAAQgDAAgCACQgCgPgDgMQgJgagWgNQgQgKgagCQg7gEgxAhQgWAPgLATQgNAXAFAXIACAIIAGgCIgBAFQABAPAIAGQAEAEAGADIgIADQAIAOAIAIQALALAeAOQAYALAOAAIAQAAQAEABADADQADADgBAEQgBAFgHADQgSAJgXgEQgQgDgXgKQgXgLgKgIQgQgNgPgYQhBAdg9AvgAC6j6QARAFAHAFQAKAGAQASQAMAPAFAJQAEAKADATQAEAZABAXIAbAJIAIgKQASgVgIgpQgEgZgLgRQgOgYgfgRIgRgIQgPgGgUgDQgdgDgQAHIgPAJIgLAIIAJAAQAZAAAZAHgAFCDsQgPAAgMgDQgKgDgEgFQgCgEAAgEQAAgFADgCQAEgDAIABIAbAAQA6gCAggWQAKgGAIgJIALgOIAFgGQgIAGgKAFIgMAGQgHAEgHACQgIADgRACQgbADgQgGQgIgDgNgHQgTgMgEgMQgBgHACgGQAEgHAJAAQAIABADAHIACAGIAEAEQAIAGALADQAWAHAfgJIANgEIAUgIQAUgJASgRQAEgFADgBQAHgCABAFQABADgCAEIgGALQAFACABAGQABADgCAHQgDALgNASIgIALQgKAOgGAGQgPAPgYAJQgiAMgiAAIgHAAgAFEBXQgGgCgCgEIgBgIIAAgMQAAgHABgCQACgFAIgCIAMgBQABAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAIABQAFAAACACQADACABAEQACAJAAAMQABAHgCAEQgEAKgMAAQgIgBgMgFgACHgtIgXgHIgTgEQgOgFgOgaIgHgPQgCgIABgNQAAgJACgGQAEgOAPgMQAKgIAGgBQAEgBAPAAQAbABAHADQAFACAJAGQAPAJAHAJQAFAGAEAIQAFAJAAAEQgBAGgDAEQgCAFgEgBQgCAAgEgIQgCgFgFgFQgKgLgQgJIgMgFIgPgBQgPAAgIAEQgGAEgEAGQgGAJADAMIAFANQAGAKAEADQAEADAKADQAdAHAKAAQAQABAEAFQAEAEgBAFQAAAFgDAEQgFAFgNAAIgFAAIgPgBg");
	this.shape.setTransform(0.046,0.0247);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AiBEhQhJgLg2gfQg0gdgZgoQgNgYgEgZQgEgbAIgYQANgmAxglQA9gvBBgdQAPAYARANQAKAIAXALQAXALAQADQAXADASgIQAHgDABgGQABgEgDgDQgDgDgEgBIgQAAQgOAAgYgLQgegOgLgLQgIgIgIgOIAIgDQgGgDgEgEQgIgGgBgPIABgFIgHACIgCgIQgFgXAOgXQALgTAWgPQAxghA6AEQAaACAQAKQAWANAJAaQADAMACAPQACgCADAAIAAAAQgBAlAEAnIABACIgBAAQgGgCgDgIIAAgCQgBAJABAGQACAJAGAGQAHAGAIgCQALgCAEgPIABgEQABgFAAgHIAAgFQBSAVBPA4QAqAdASAbQAJANABAKIgDADQgIAMgBAFQgFAOAIAbIAFAMQAAALgCAHQgEALgNAOQhKBOhnAcQg6AQhZACIgVAAQhAAAgygIgACMDBQgDACAAAFQAAAEACAEQAEAFAKADQAMADAPAAQAlACAmgOQAYgJAPgPQAGgGAKgOIAIgLQANgSADgLQACgHgBgDQgBgGgFgCIAGgLQACgEgBgDQgBgFgHACQgDABgEAFQgSARgUAJIgUAIIgNAEQgfAJgWgHQgLgDgIgGIgEgEIgCgGQgDgHgIgBQgJAAgEAHQgCAGABAHQAEAMATAMQANAHAIADQAQAGAbgDQARgCAIgDQAHgCAHgEIAMgGQAKgFAIgGIgFAGIgLAOQgIAJgKAGQggAWg6ACIgbAAIgEgBQgFAAgDADgADEAbIgMABQgIACgCAFQgBACAAAHIAAAMIABAIQACAEAGACQAMAFAIABQAMAAAEgKQACgEgBgHQAAgMgCgJQgBgEgDgCQgCgCgFAAIgIgBQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAgAgvi+QgGABgKAIQgPAMgEAOQgCAGAAAJQgBANACAIIAHAPQAOAaAOAFIATAEIAXAHQAKABAJAAQANAAAFgFQADgEAAgFQABgFgEgEQgEgFgQgBQgKAAgcgHQgKgDgEgDQgEgDgGgKIgFgNQgDgMAGgJQAEgGAGgEQAIgEAPAAIAPABIALAFQAQAJAKALQAFAFACAFQAEAIACAAQAEABACgFQADgEABgGQAAgEgFgJQgEgIgFgGQgHgJgPgJQgJgGgFgCQgGgDgbgBQgPAAgEABgAB7iEQgBgXgEgZQgDgTgEgKQgFgJgMgPQgQgSgKgGQgHgFgRgFQgdgIgdABIALgIIAOgJQAQgHAdADQAUADAPAGIARAIQAfARAOAYQALARAEAZQAIApgSAVIgIAKIgbgJg");
	this.shape_1.setTransform(14.2333,1.73);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.9,-35.7,115.9,71.5);


(lib.stop_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7D016E").s().p("AjtEAQgagQgLgmQgEgSgBgYIgDgKQgDgLADgPIAGgVQABgMADgJQACgSAAgdIgBinQgBgiAFgVQAGgeASgRQAOgNAZgGQAQgEAegCQDBgNByAJQAgADAVAFQAcAIARARQAUATAHAjQAFAZgBAmIgDBbQgBA0AEAmIAGA1QACAggFAWQgGAcgSAUQgSAUgXAEQgMAGgPACQgNACgYAAIjIACQg5AAgdADIg1AGQgeAAgUgMg");
	this.shape.setTransform(28.4615,26.7866);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,56.9,53.6);


(lib.reply_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0099").s().p("AjIM4Qg1gQhngqQgxgUgYgNQgogUgbgXQgzgsgfhJQgYg6gPhTIgDgXQhBBBhLBEQgYAVgOAJQgWAQgVAEQgYAGgYgIQgYgHgRgRQgRgSgHgYQgGgZAFgXQAJggAegdQASgRArgdQBjhDBPhQIAdgeQASgQAQgJQATgKAVgCIAFAAIAIgDQAbgJAcAHQAYAFAbAQIAvAdQA0AiA6AXIBJAbQArARAaASQAiAYARAjQAUAlgKAkQgGAZgUATQgVASgaAEQgaAEgegKQgUgGgigSQg0gbgpgXQAMAhATAVQAQASAYAOQASAKAdANQDDBSCpgCQBhgBBYgcQBegeBGg6QAuglArg3QAbgiAegwIADgQQAIgsAYhGQAdhTAHgeQAbhkgGhtQgEg2gMgqQgbhjhXheIgWgZQgMgOgEgOIgCgIQhNg8hEgnQhYgzhVgZQhfgbhdAHQhkAHhOAuQh3BFhOCgQggA/gJAzIgHA4QgGAhgKAUQgMAYgVAQQgWAQgaAFQgaAFgagJQgagIgSgTQg2g7ApiCQA8jBBph9QA8hHBLgwQBPg0BWgSQAegGAigDQAygRAygJQDAgfDgBXQCVA6BvBdQB8BlA9CCQAlBNAUBjQAuDqhFDtQhGDtimCtQg7A9g8AoQhNAzhqAhQiNAsiVABQiUAAiNgrg");
	this.shape.setTransform(95.831,86.7081);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0099").s().p("AktTVQhQgYiag/QhJgeglgTQg8gegogkQhMhBgvhuQgkhXgWh9IgFgiQhiBhhxBmQgjAggVAOQgiAXgfAHQgjAIglgLQgkgKgagbQgZgagKglQgKgkAJgkQAMgwAugrQAbgaBBgrQCUhkB3h5IArgsQAbgYAYgOQAcgPAggDIAHAAIAMgEQApgOAqAKQAkAIAoAYQAOAHA5AlQBOAyBYAjQAkAPBJAaQBAAZAnAbQAzAkAaA0QAdA4gOA2QgKAmgeAcQgeAcgnAGQgnAGgugPQgegKgygaQhPgqg9giQASAyAcAgQAYAaAlAWQAaAPAsASQEkB8D+gDQCSgBCEgrQCNgtBqhXQBEg4BAhSQApgzAuhIIADgYQAMhCAkhpQAsh9ALgsQAoiXgJijQgFhRgSg/QgpiWiDiNIghglQgRgVgHgVIgDgMQh0hahlg7QiFhNh/gkQiPgpiLAKQiWAKh2BFQizBph1DvQgvBfgOBMQgEAcgHA4QgIAygPAfQgSAjggAYQghAZgnAHQgnAHgngNQgngNgbgcQhRhZA+jDQBakhCdi8QBahrBwhIQB4hNCAgbQAtgKA0gEQBKgaBMgMQEggwFRCEQDeBXCoCKQC5CZBcDCQA4B0AdCUQBGFfhoFlQhpFkj5EDQhYBchaA8Qh1BNifAxQjTBCjgABQjfAAjThAg");
	this.shape_1.setTransform(95.8837,86.7448);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0099").s().p("AitLKQgvgNhZglQgqgQgVgMQgigRgYgVQgsglgbhAQgVgygNhIIgCgVQg5A5hBA7QgUASgNAIQgTAOgSAEQgVAFgVgHQgUgGgQgPQgOgQgGgVQgGgVAFgUQAIgcAagZQAQgPAlgZQBWg6BEhFIAZgaQAQgOAOgIQAQgJASgCIAFAAIAHgCQAXgHAYAFQAVAEAXAOIAqAaQAsAdAzAUIA/AYQAlAOAXAQQAdAVAQAdQARAigIAeQgHAXgRAPQgSAQgWAEQgXADgbgJQgRgFgcgPQgugYgjgUQAKAdARASQANAPAWANQAOAJAaALQCpBHCSgBQBUgBBOgZQBQgaA9gzQAoggAmgvQAXgeAagpIADgPQAGglAVg9QAahIAGgaQAWhWgEhfQgEgvgKgkQgXhXhMhRIgTgVQgKgNgEgMIgCgHQhDg0g6giQhNgshKgVQhSgYhRAGQhWAGhEAnQhoA9hDCLQgcA2gHAsIgHAxQgEAdgJARQgKAUgTAPQgTAOgWAEQgXAEgWgHQgXgHgQgRQgvg0AkhwQA0ioBbhsQA0g9BBgqQBFgtBKgPQAagGAegDQArgPArgHQCngbDDBLQCAAzBhBQQBrBYA1BxQAhBDARBVQAnDLg8DNQg8DPiQCWQgzA1g0AjQhDAshcAcQh7AniBAAQiAAAh6gmg");
	this.shape_2.setTransform(95.8828,86.7176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47.9,-43.3,287.59999999999997,260.2);


(lib.play_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7D016E").s().p("AihDwQgRgGgMgMQgZgaACgmQAAgKAFgRIAGgbQADgRgCgdQgBgjABgMQAAgKAJgvQAGgjgDgWQgHgbgBgOQgEghAVgdQAVgdAhgHQAXgEApAKQAGgBAGACQAHABAIAFIAjAKQAZAJARAMQANAIASAQIAdAZQALAJAaAQQAZAQAMAKQAqAkgEApQgDAbgfAhQgpAphOAwQhqBCgUAPQgUAPgJAGQgRAKgQADIgLABQgMAAgLgEg");
	this.shape.setTransform(21.4379,24.3657);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,42.9,48.8);


(lib.pause_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7D016E").s().p("Ah7ExIgOgEIgMgGIgIgGIgIgGIgGgGIgEgGIgEgGIgEgGIgCgGIgEgGIgCgCIgGgGIgEgGIgEgGIgCgGIgCgGIgCgGIgCgGIAAgGIAAgGIgCgGIACgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgFIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIACgGIACgGIACgGIAAgGIACgGIACgGIACgGIAEgGIAGgGIAGgGIABgBIABgDIAAgGIACgGIACgGIAAgGIACgGIAEgGIACgGIAEgGIAGgGIAGgGIAIgEIAGgCIAMAAIAAgCIAQAEIAKAGIAIAGIAEAGIACAGIAEAGIACAGIACAGIACAGIACAGIACAGIAAAGIAAAGIACAGIAAAGIACAGIAAAGIACAGIAAAGIACAGIAAAGIAAAGIACAGIAAAGIACAGIAAAGIACAGIACAGIAAAGIACAGIAAAGIAAAGIACAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAFIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIgCAGIAAAGIAAAGIgCAGIAAAGIgEAGIgCAGIgCAGIgEAGIgEAGIgEAGIgIAGIgIAGIgIAGIgKAEIgEACIgIACIgSACIgSgCgABkElIgQgEIgMgGIgMgGIgGgGIgGgGIgGgGIgGgGIgEgGIgCgGIgEgGIgCgGIgCgGIAAgGIgCgGIAAgGIAAgGIgCgGIACgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgFIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIACgGIAAgGIAAgGIACgGIAAgGIAAgGIACgGIACgGIAEgGIACgGIACgGIAEgGIAEgGIAGgGIAGgGIAIgGIAMgGIAMgEIAQAAIAAgCIAQACIAMAEIAKAGIAKAGIAGAGIAEAGIAEAGIAEAGIACAGIAEAGIACAGIACAGIACAGIACAGIAAAGIAAAGIACAGIAAAGIACAGIAAAGIAAAGIACAGIAAAGIAAAGIACAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAFIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIACAGIAAAGIAAAGIAAAGIgCAGIACAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIAAAGIgCAGIgCAGIgCAGIgCAGIgEAGIgCAGIgEAGIgEAGIgGAGIgGAGIgIAGIgKAGIgOAGIgOAEIgSACIgSgCg");
	this.shape.setTransform(21.6,30.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,43.2,61.4);


(lib.horay_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#8F8F8F").ss(1,1,1).p("ECXwBVwMkvfAAAMAAAirfMEvfAAA");
	this.shape.setTransform(971.2,548.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC00CC").s().p("Eg8RAd3QglgTgSgkQgQgfgEgrQgDgcACgzQAYn6ALkJIg3AkQguAfgbANQgrAUgmAEQgsADgmgWQgpgYgHgoQgGgbAMgeQALgaAWgWQASgRAcgSIAzgdQA/giBLgyIBLgzQAIk1gGjpIgQl0QgJjiACiUQADiHATkOQACgdADgQQAEgZALgRQAMgUAWgJQAXgKATAJQAVAJAKAcQAHATACAgIARE4QAdH1AKEGQALEMACDrQE6jdCrh7QC0iBBeg/QgVkAgfjzIgYi+QgLhtAAhTQABgvAGgfQAJgqAWgbQAagfAqgFQArgFAYAdQAQAUABAiQAAAPgFAtQgIBGAJBYQAFAwASBuQAnD0AcD1QBSgyBMgnQAdgOARgHQAbgKAXgBQAbgCAXALQAaALALAWQALAVgEAaQgEAYgPAVQgMASgVARIgoAdQhVA7iTBoQAxIigIIlQgCBhABApQADBNALA7QAMA/ABAVQADAugVAdQggArg+gKQg8gJghgvQgbgpgJg9QgFgnAChIQAOpdggojIk0DeQkJDAjMCPQgDDWgRGfIgOFcQgCA5gMAiQgRAwglAPQgPAGgPAAQgVAAgWgLgEBAeAdJQgTgCgegKQgdgIgQgIQgXgLgOgRQgTgXgIgvQgJg6AChIQABgdAEguIiGvGQgfgXgOglQgKgZgCggQgmgbghguQgYgggkhCQjxm0ivlTQjYmkiolzQgTgqgHgZQgMgmACggQADgmAYgdQAZgeAigCQAlgCAiAiQAYAYAYAvIHLNhQDAFiCmEfIAPhLQBOl2AbnxQAKiuARrDQABgwAFgaQAHgoATgbQAWgfAogIQAqgIAXAbQAMAOAFAWQADAPACAbQAaIGgBEnQgDHBg4FnQgLBGgpDiQgiC5gOBxQgGAvgEAQIgCALQBcFvApDMQAyD8AZDgQANAiAEArQAFArgDBOQgCA6gJAbQgQAwgmAQQgOAGgTAAIgPgBgAVkYYQgVgCgRgRQgPgPgGgXQgFgSABgZIAFgrQAhjeAJkYQAFimgClTQgClQAGioQAJkYAijeQAOheASg+QAHgXAIgVQg5hpArgyQAVgZAkgCQAjgCAeASQAIAEAIAGQAKgCALACQAVADAMAOQAMAOAAAUQABAMgDALIAJAOQL6SBOUQIQAgAlANAWQAUAkgDAgQgEAwgwAcQgtAagzgJQgrgIgtggQgfgXgqgsQg9g+hGhUQgrgyhRhlQnGo2j6lUIgLAKQggAggRAOQgRAOgiAWQgkAXgQANQgSAOgbAaIgrAqQghAfhQA5IiKBjQglAbgXALIgHADQgFFkgbDqQgKBTgNAyQgTBIgjAyQggAuglAAIgDAAgAYRibQAABhAGF3IACBqIAkgXQBFgsApggIAzgrQAggdATgPQAagUAmgZIBCgrIBYg8QkHlvjGlPQgNDIAAECgARNXvQgigBgggPQgbgNgdgYQgTgPgfgfQoAn5m4oxQgmgwgSgcQgcgrgOgoQgPgvAEguQAFgyAcgjQAeglAygHQAvgHAgAaQCWiEBMhJQCfiZBoiMQAigvATgjQAagvAKgsQANg+gQhDQgPg/gmg3QhFhjiEg/Qi3hXjSAcQjTAbibCDQAQAdgNAgIAAAOQAAAwAMA7QAHAhAUBHQAxC2A0DlQAfCIA8EUQAuDSATBrQAgCwAMCPQAFA+AHB8QAIBtAPBKIAYBlQAQA/AGAmQAPBTgiAnQgbAhgwgDQgvgDghgfQgdgbgSgtQgNghgLg0QgVhngOiWQgOirgJhVQgTi/gqjtQgZiMg6kdIiWraQgMg7gBgiQgBg1ASglIAGgJQAKg4BAg+QBohlCJg8QCIg7CQgHQCRgICOAtQCNAtBzBaQCHBqA+CMQAhBKAJBPQAIBSgUBMQgNAzgeA5QgWArgmA5QhiCRhyB+Qg6BAhvBrIilClIAmAtQGoHqHLHAQAuAtATAXQAiApAOAnQARAvgLAwQgMAygmAYQgbAQgjAAIgCAAgA4JTsQgggFgvgNIhNgWIhDgRQgngKgagLQhYgkhPhUQhdhkhMimQhQiygkjBQgkjCAKjCQAKiyAviNQA4ipBlhlQBehdCrhDQDchVCoAbQCPAXB/BnQBzBdBTCMQBhCkAtDMQApC5gDDRQgGGKiqDyQhjCPiZBMQh5A8h6AAQgnAAgngGgA2oPTQAcAdgJAhQBwgSBfhUQBXhPAyhxQAshjARiAQANhgABiNQABhsgHhKQgKhkgahOQgUg7glhFQgWgrgwhPQgxhSghgpQgzhAg7geQhPgphuALQhSAIhwApQg9AVgnAUQg0AaglAgQhDA8gqBtQgwB4gLChQgODUAwDSQAwDSBpC5QAYAqATAZQAaAjAdAWQBAAwBmAGQApADAYgKQANgGAdgWQAZgUASgFQAIgCAHAAQAZAAAWAWg");
	this.shape_1.setTransform(978.4948,590.1133);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0099").s().p("EhFvAyIQgjgGgJgaQgJgZAWgbQASgUAggRQBug4CMg3QBhgmChg4QQ+l4RikCQRjkCR1iHQIehAMag9QMGg8HogLQK1gPI4A+QA6AGAOAcQAJASgKAWQgJAUgTALQgRAJgXADQgPACgcAAQ/tAK69DVQ+yDz6lIJQm4CLjdBEQmDB4kZBBQgYAGgVAAIgTgCgEhJ7givQgPgCgZgIQirg1iNhjQhBgvAJgtQAGgXAYgOQAWgMAaACQAWACAaALIAsAXICTBKQBYArA1AnQAkAbACAZQACATgPARQgOAQgVAFQgJACgLAAQgJAAgLgCgEhHnglIQgegIgpgaQhXg2gqgdQhHgwgygvQhJhCAKg7QAEgYASgTQASgSAYgFQAlgHApAaQAVANAuAqQA6A0BFAoIBGAnQAnAYAUAbQAaAigCAqQgCAtghAUQgRAKgWAAQgPAAgQgEgEBLJgpAQgbgHgLgfQgLgcAKgdQAIgXAVgZQAJgLAfgfQB3h3BGiaQAQgiAQgJQANgHAPADQAPACAMAKQAVATAEAhQADAegMAjQgIAagUAkQhVCah3B3QgrAqgiABQgHAAgGgCgEBIfgqwQgUgIgHgSQgJgYAVgmQAOgcAbgmIArg/QAuhFAhhMQAQglAHgNQAOgbATgPQAWgSAdgBQAfAAAPAVQAOATgFAdQgDAVgOAdQgzBwgeA3QgzBZg5A7QgjAkgeAHQgHABgHAAQgNAAgMgFg");
	this.shape_2.setTransform(976.4543,646.1134);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9B9FDA").s().p("ECUaBVwMkvfAAAMAAAirfMEvfAAAIGsAAMAAACrfgEAudApJQnoAKsGA8QsaA+oeBAQx1CHxiEBQxjECw+F5QihA3hgAmQiMA3hvA4QgfARgSAVQgXAaAJAZQAJAaAjAHQAcADAkgIQEZhBGDh3QDdhEG5iMQakoIezjzQa8jWfugKQAbAAAPgBQAXgDARgKQAUgLAIgUQAKgVgJgTQgOgbg6gHQnGgyoWAAQiGAAiLAEgEg/qAhEQgCAzADAcQAFArAPAfQASAlAlASQAnAUAigPQAmgOAQgxQAMgiACg5IAPlcQAQmeADjXQDNiPEIjAIE0jeQAgIkgOJdQgCBHAGAoQAIA8AcApQAgAvA8AJQA/AKAfgqQAVgegDguQgBgVgMg/QgLg7gDhNQgBgpAChhQAJolgyoiQCThpBWg6IAngdQAVgSANgRQAOgWAEgYQAEgagLgVQgLgVgagMQgXgLgbACQgXACgbAJQgRAHgdAOQhLAnhTAyQgcj0gnjzQgShvgFgwQgIhYAHhFQAGgugBgPQgBgigQgUQgXgdgsAFQgqAGgZAeQgXAbgJAqQgGAfAAAwQgBBTAMBsIAXC+QAfDyAVEAQheBAizCBQisB7k5DdQgDjrgKkMQgLkHgdn0IgRk3QgCghgHgTQgJgcgVgJQgUgJgXAKQgWAJgMAUQgKASgFAYQgDAQgCAdQgTEOgCCHQgDCUAKDhIAPF1QAGDpgIE1IhLAzQhLAyg/AiIgyAeQgdARgSARQgWAWgLAbQgMAdAGAbQAHAoApAYQAmAWAtgDQAmgDAqgVQAbgNAvgeIA2gkQgLEIgYH6gEArBgRVQgiACgZAfQgYAdgDAlQgBAgALAmQAHAZATAqQCoFzDZGkQCuFSDxG1QAkBCAYAgQAiAvAlAaQADAgAJAZQAPAlAeAXICGPHQgEAtgBAdQgCBJAJA5QAIAvATAXQAOARAXALQAQAIAdAIQAeAKAUACQAbADAVgIQAmgQAPgvQAKgcABg6QADhOgFgrQgEgrgNgiQgYjggzj8QgpjMhcluIACgLQAEgRAGguQAOhyAii4QAqjjAKhGQA5lnACnBQABkmgaoHQgBgbgEgOQgFgXgMgNQgXgcgqAJQgnAHgWAfQgUAbgHAoQgFAagBAxQgRLCgKCuQgbHwhOF3IgPBMQimkhjAlhInLthQgYgvgYgYQgggggkAAIgDAAgAVTo1QgkADgVAYQgrAzA5BpQgIAUgGAYQgTA9gOBeQgiDdgJEYQgFCqABFPQADFTgGCmQgIEZgiDdIgFArQgBAZAFASQAGAXAPAPQARASAVABQAmACAigwQAjgyAThHQANgzAKhTQAcjqAEljIAHgEQAXgLAlgaICKhkQBRg5AggfIAsgpQAagaATgPQAPgNAkgXQAjgWAQgOQARgOAhggIAKgKQD6FUHGI2QBRBlArAyQBGBUA9A/QAqAsAfAWQAtAgArAIQAzAKAtgbQAwgcAFgwQADgggVgjQgNgXgggkQuUwIr6yCIgJgNQADgMAAgMQgBgUgMgOQgMgOgVgDQgLgBgKABQgIgFgHgFQgcgQgeAAIgIAAgAifGBQgzAHgeAmQgcAjgFAzQgEAtAQAvQANAoAcArQASAcAmAwQG5IyH/H4QAfAfATAPQAdAYAbANQAgAQAiAAQAlABAbgRQAmgYAMgyQAMgvgRgwQgPgmgigpQgTgYgugtQnKnAmpnpIgmguICmilQBuhsA6hAQBzh+BhiRQAmg4AWgrQAeg5AOgzQAThLgIhSQgIhQgihKQg9iLiIhrQhyhaiOgtQiOgsiQAHQiRAHiIA7QiIA8hpBlQhAA+gKA4IgGAJQgSAlABA1QABAiANA8ICVLZQA6EdAZCMQAqDtAUDAQAIBUAOCrQAOCWAWBnQAKA0AOAhQASAtAdAbQAgAfAvADQAxADAbghQAigngPhTQgGgmgQg/IgZhlQgPhKgIhtQgHh8gFg+QgLiOghixQgThrgujRQg7kWggiHQg0jlgxi1QgUhIgGghQgMg7gBgvIAAgOQANghgQgdQCbiDDUgbQDRgbC4BWQCDA/BFBjQAnA4APA+QAQBDgOA/QgKArgaAvQgSAjgjAvQhoCMifCYQhMBJiVCEQgZgUgjAAIgTABgA+1krQirBDheBdQhlBlg4CoQguCNgLCzQgKDCAkDCQAlDBBPCyQBMCmBdBkQBPBUBYAkQAbALAnALIBCARIBOAVQAuANAgAFQCgAaChhQQCZhMBjiOQCqjzAHmKQACjRgpi6QgtjLhhilQhTiLhyhcQiAhoiOgXQgpgGgrAAQiKAAinBAgEhSWgYFQgYAOgFAXQgKAtBBAvQCOBjCrA1QAZAIAOACQAWAEATgEQAUgFAOgQQAPgQgCgUQgBgZglgbQg1gmhYgsIiThJIgsgYQgagLgVgCIgIAAQgWAAgTAKgEhPIgcNQgXAEgTASQgSATgEAZQgJA6BIBDQAzAuBGAwQAqAdBYA3QAoAZAeAIQApALAdgRQAigUABgtQACgqgZghQgVgcgngYIhGgnQhFgng6g1QgugpgVgNQgggVgeAAIgQACgEBMjghoQgQAJgPAjQhHCZh3B3QgfAggJAKQgVAZgIAXQgJAdAKAdQAMAeAaAHQAnAKAzgzQB3h3BViaQAUgjAIgbQANgjgEgeQgEghgVgSQgMgLgPgCIgHgBQgLAAgKAFgEBJ9gi7QgdAAgWASQgTAPgOAcQgHAMgPAlQghBNgvBEIgrA/QgbAngOAbQgVAmAJAYQAHASAUAIQATAJAUgFQAegHAjgkQA6g6AyhaQAfg3AyhwQAOgdAEgVQAEgdgOgTQgPgVgeAAIgBABgA41VwQgcgcgiAJQgRAEgaAUQgdAXgNAFQgYALgpgEQhlgGhBgwQgdgWgagjQgTgZgYgpQhpi6gwjRQgwjTAPjUQAKiiAwh4QAqhtBDg6QAlghA0gaQAngUA9gVQBwgpBTgIQBtgKBQApQA6AdAzBAQAhAoAxBSQAwBPAXArQAkBFAUA8QAbBOAJBkQAHBKAABtQgCCMgNBgQgRCAgrBjQgzBxhXBPQhfBVhwASQAJgigcgdgAWKLaQgGl4AAhgQAAkCANjHQDGFNEHFwIhXA8IhDArQgmAZgaAVQgTAOggAdIgzArQgpAhhEArIglAXIgChqg");
	this.shape_3.setTransform(992.55,548.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.horay_mc, new cjs.Rectangle(-1,-1,1986.1,1099.6), null);


(lib.cursor_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A900").s().p("AAFA3QgBgBgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIABgFIADgIIgEgDIgCgDIgLgWIgBgFIgBAMQAAAKAFARQACAFgCACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAIgEgEIgCgKIgCgVIABgVIABgHIgBgBIgBgLIAAgCIgBACQgGAHgDALIgFAcIgBAMIAAAEQAAABAAAAQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgBgEIABgPIADgSIADgMQAEgJAEgFIACgFIACABIADgCIABgBIADgGIAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAAgBIADgBIAAABIADgCIAJgEIAHgEIACACIgBgBIABgCIAEgCIADAAIADAFIABABQAHAGAFAJIABAFIACAFIAEAIIACAGIABAHIABAGIABAMQgCAIgCAEQgEAGgFAAIgEgDIgDgDQgDgCAAgEQABgDACgBIACgEIADgNIABgFIgBgQQgHgPgDgDIgBgBIACAEIAAAAIADAGIACAMIgBAKIAAAAIgBAHIgBAAIgCACQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgBgEIAAAAIAAgFIAAgBIAAgBIAAgBIAAgFIAAgHIAAgDIgEgKIAAgBQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgBgBIgBgCIgEgEIgCABIAGAJIADAHIACAJIADAfIgBAWIACADQAAABAAAAQABABAAAAQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAIgBAAIgDAIIgCAEIgDABIgBAAgAgKgZIgBAFIADAMQAIASAIAOIAAgNIAAgKIAAABQgBAAAAAAQgBAAAAAAQAAABAAgBQgBAAAAAAIgCgBIgCgDIgBgCIAAgCIAAgBIgBgDIAAgBIgCgCIgEgMIgBgBIAAgFIgCAGgAgDglIAAADIABABIAAAFIAAABIABADIABAEIAAAAIAAACIABACIAAAAIAAABIABABIAAABIABABIABACIABACQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAACIABAAIABADIAAACIAAgBIgCgVIgDgIQgCgFgCgFg");
	this.shape.setTransform(13.1,29.0417);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3300").s().p("AgqBMIAAgBIAAAAQAJgLALgJIAKgJQAWgRAOgHIAMgEQAIgDAHgBIAKAAIABABIABAAIABACIAAAAQgbABgYAOIgMAJQgNAJgJAJIgKAKIgDADQgEAEgDAAgAg1ANQgCgBABgFIAEgHQAFgJAJgIIACgCIAFgEQACgBACgCIAUgIQAOgEAPAHIACACQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgCgBQgLgCgLAAIgEABIgKAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgCABQgGADgHAHIgGAGQgFAFgEALIgCADIgCABIgBAAgAg/gpQgBgFACgEIABAAIABgDIALgOQAAAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIAFgCIACgCIAGgCQAHgBANgBIAEACQABAAABABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBgBAAIgSABIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIgEABIgFACQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABgBAAIgDAEQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABAAAAIgCACIAAABIgCABIgCAEIAAACIABABQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIgBABIgDgBg");
	this.shape_1.setTransform(7.0741,12.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF6600").s().p("AAcCFIACgCIAAACIgCAAgAASCFQgXgBgKgIQgFgDgIgKQgQgWgEgMIgDgLIAAABQADAAAFgFIADgCIAKgLQAJgIAOgKIALgIQAYgOAagCIABAAIAPAUQAGAIACAFQACAGAAAPQABAZgGANIgEAKIgBgBIgEgFIgCAAIgEACIgBACIABABIgCgCIgHAEIgKAEIgDACIAAgBIgDABIAAABQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABIgBAAIgCAGIgBABIgDACIgCgBIgDAFIgDAAgAAqB+IAAAFIABABIgDAAIACgGgAAvCBIAAgFIAAgBIgBgDIACgDQAEAFACAFIgEACIgCABgAA2BxIACgBIAEAEIABACIABABIgCADIgGgJgAg2A4IgShkQgHgtAAgYIACgIIAEgEIAFgEQAJgGAKALQAHAHAKASIAYAaIA9BOIgCAAIgKgBQgGABgJADIgLAFQgPAGgVARIgKAJQgMAJgIALIgDgJgAgPgsIgTAIQgCACgDABIgFAFIgCABQgJAIgEAJIgEAJQgCADACABQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABgBIABgCQAEgLAGgGIAFgGQAIgGAGgDIABgCQABAAABAAQAAAAABAAQAAgBABAAQAAAAABAAIAKgEIAFgBQAKAAALADIACAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIgCgCQgJgFgJAAIgLABgAgshUIgGACIgCACIgFACQAAAAAAABQgBAAAAAAQAAAAAAAAQAAABgBAAIgKANIgCADIgBABQgCADACAFIADABQABgBAAAAQAAAAAAgBQABAAgBgBQAAAAAAAAIgBgBIABgBIACgEIACgCIAAgBIACgCQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAABAAQgBgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIADgEQAAAAABgBQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIAGgDIADgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIABAAIATgBQAAAAAAABQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgFgBQgNAAgGABg");
	this.shape_2.setTransform(8.0321,13.2441);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.cursor_mc, new cjs.Rectangle(0,0,17.5,34.6), null);


(lib.carrot05_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF2F02").s().p("Ag+AQIAAgNIABgFQABgEADgCQAAgBABAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABIgBACQgDACgBACIgBADIAAAKQABAEgCABIgCACQAAAAAAgBQgBAAAAAAQAAAAgBgBQAAAAgBgBgAAxAQIgBgBIAAAAIgBgDIgBAAIgBgBIAAgIIABgBIAAgDIABAAIAAgDIAAAAIAAgBIABAAIABgFIABAAIAAgBQABAAAAAAQAAAAABAAQAAgBAAAAQgBAAAAgBIAAAAQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBIABgBIABAAIADgBIACABIABABIABABIgBAAIAAABIgCABIgBABIgBABIAAAAIgBABIAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIAAABIgCABIAAABIAAABIgBAAIAAACIAAAAIAAACIgBAAIAAAJIACABIAAACIAAADIgBAAIgBABgAgbALIgBgFIAAgFQABgJABgDIADgEQACgCAEACQAAAAAAABQABAAAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQgBAGAAAGIAAAHQAAABAAABQAAABAAABQAAAAgBABQAAAAAAAAIgCABQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBgBAAgBgAANAFIAAgEIgBgJIABgBIABgDIACgEQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAIABgBIACABIABACIgBABIgDACIgDAFIAAAEIAAAIQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAg");
	this.shape.setTransform(15.2,9.6021);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AiKAYIgBAAIAAgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIgBgBIAAgBIAAgBIAAAAIABgBIAAgBIABAAIACgDIAIgEIAbgHIAHgCIAlgKIAJgCQBbgTBbATQABABABAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIABAAIABAAIAAABIAAACIAAABIgCACIgFAEIgBACIgBADIABACIAAAAIABABIAAAAIABABIAFACIABABIABAAIABABIABAAIABACIAAAAIABADIgBAAIAAABIgBAAIgBACIgGAAIgDgBIgBAAIgGAAIgVAAIiiABIgSAAIgHAAIggABIgEACIgJAAIgIABgAgwgNQgDADgBAEIgBAFIAAANQADADACgCQACgBgBgFIAAgIIABgFQABgCADgCIABgCQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQgBABAAAAgAA3gCIgBABIAAAHIABABIABAAIABADIAAAAIABACIADAAIABgCIABAAIAAgCIAAgCIgCgBIAAgJIABAAIAAgDIAAAAIAAgBIABAAIAAgCIAAgBIACgBIAAgBQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAAAIABgCIAAAAIABgBIABgBIACAAIAAgBIABAAIgBgCIgBAAIgCgBIgDAAIgBAAIgBACQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAgBABIAAAAQAAAAABAAQAAABAAAAQgBAAAAAAQAAAAgBAAIAAACIgBAAIgBAEIgBAAIAAACIAAAAIAAADIgBAAgAgOgUIgDAEQgBAEgBAKIAAADIABAGQACAEADgDQAAAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgGQAAgHABgHQABAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAIgDgBIgDABgAAdgWQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBABIgCADIgBADIgBACIABAKIAAACQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIAAgHIAAgFIADgFIADgBIABgCIgBgCIgCAAg");
	this.shape_1.setTransform(14.3,10.0812);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#667400").s().p("AguAcIgBgBIABgCIAKgCIAEAAIAqgKIAjgJQAAAAABAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgCACIghAJIgVAFQgUAFgNABIgCAAIgCgBgAABgOQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIACgCQAEgCAKgDIAFgDIAGgCIACAAIAAABQAAAAAAAAQABABAAAAQAAAAgBABQAAAAAAAAIgJAEQAAAAAAABQgBAAAAAAQAAAAgBABQgBAAAAAAIgOAFIgCAAIgBAAg");
	this.shape_2.setTransform(36.2917,7.42);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A900").s().p("AhbA8QgHAAgEgBIgCgBIAAgBIABgBIAAAAIAAgDIgBAAIgBgBIgBAAIgBgBIgBAAIgBgCIgEgBIgBgBIgBgBIgBgBIAAAAIgBgBIABgEIACgDIAEgEIACgCIAAAAIAAgDIAAAAQASgWAXgSQAggaAhgMIAMgFQAbgHAYABIAFABQAEADgCAEQgDAHgOAHQgSAHgeAQIgCAAIgFACIgFADQgKADgEACIgCACQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIAOgFQAAAAABAAQAAgBABAAQAAAAABgBQAAAAAAAAIAIgEQAAAAAAAAQABgBAAAAQAAAAgBgBQAAAAAAAAIAPgFQAmgKAoADIAOACQAFABACADQADAEgEAEQgCACgGACIgRAGIgOAFIAKAAQAHABABABQAEADgBAGQAAADgEAGQgGAHgNAGIgGADQgOAGgdAIIgcAHIgZADgAgQAZIgrAKIgEAAIgKACIgBACIABABQAAABABAAQAAAAABAAQAAAAABAAQAAAAABAAQANgBAUgFIAWgFIAggJIACgCQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(38.9981,6.2233);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot05_mc, new cjs.Rectangle(0,0,50.8,12.6), null);


(lib.carrot04_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A900").s().p("AglBIQgJgCgIgGIgIgGQgFgLACgNQACgJAGgGQADgEAIAAIgSgEQgdgLgLgYIgEgNQgDgGABgHQgBgLAIgIIAjgDQAMADAVAJIAGADIAAgDIAFgGQAFgCAFAAIALgBIAMABQAIABAHAGIAOALIAFAHIAIADIAEAHQAJAJAAADQAHAFAMAQIAAADIAIAHIAMAUIAHARIABAFIgCAGQAAABAAAAQAAABgBAAQAAAAgBAAQgBABAAAAIgBAAIgJADIgWACQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAgBIhgAHg");
	this.shape.setTransform(11.1375,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot04_mc, new cjs.Rectangle(0,0,22.3,14.6), null);


(lib.carrot03_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A900").s().p("AhjA/IgBgCQgCAAgCgGIgBgOIgDAAQgDAAAAgFQAAgFACgEQAKgbAJgNIASgUQAfggA2gCQAqABAcARQAEADABADQACAEgEAGQAKADALAGQAGAEgBADQAAADgFADQgSAJgigBQgngBgPAEQgPACgVAMIgYAQQANgGAQgDQAHgCAFAAIAmgCIAMADIAZAIQAGACADAEQADADAAADIgFAEQgGAEgWADIhoAMQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABIgFABg");
	this.shape.setTransform(11.2077,6.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot03_mc, new cjs.Rectangle(0,0,22.4,13.5), null);


(lib.carrot02_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6600").s().p("AgqAUIgBgBQgDgCACgDIAEgEQAIgIAKgEIAAACIAAAAIAAABIABABIAAAAIAAACIABAAIAAABIABABIAAAAIACABIABgBIABgBIAAgBIgCgEIgBAAIAAgCIgBAAIAAgBIgCAAIAIgEIAFgDIAHgCQAOgFAIgBIALgBIADABIAAgBIACgBIACABIADACQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAIAAACIABAAIABACIAAABIAAADIgBADIgBABIgBABIgEABIAAAAIgBABIgBABIgCABIgIAFIgCABIgBAAIAAABIgFACIgDADIg3AGgAgBgLIgBAFIAAACIACADIAAAAIAAABIAEACQADABACgBIAAgBIgBgBQgEgCAAgCIgBAAIAAgBIgBgCIAAgCIgBgCIgBgBIgBABg");
	this.shape.setTransform(4.5719,12.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3300").s().p("AgMAJIAAAAIgBgBIAAgBIgBAAIAAgCIAAAAIgBgBIAAgBIAAAAIAAgDIAAAAIABAAIACAAIAAAAIABAAIAAADIABAAIACAEIAAABIgBABIgBABgAALAFIgEgCIgBgCIAAAAIgCgCIAAgCIABgFIADAAIABACIAAACIABACIAAABIABAAQAAABAEACIABACIAAABIgCABIgDgBg");
	this.shape_1.setTransform(3.875,11.9375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A900").s().p("Ag1A8IABgBIABgEIAAgCIACAAIABgEIgBAAIgBABIgBACIgBgDIAAAAIgBgBQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAIgDgCIgBgBIgBgFQgBgRAQgbQASghAUgKQAHgEALgDQAGgCAFAAQAEAAABADQABACgCAEQgEAKgMANIgSAZQAMgJAPgFQASgGAPABQAEAAACACQADACgBADQAAABgDADIgWASIgRAOIAQAAIAFADIACACQABADgEACIgQAIIgwATIgVABIgGAAgAgbAlIgNAGIAAADIAVgLIAEgCIgMAEg");
	this.shape_2.setTransform(14.3005,5.9958);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot02_mc, new cjs.Rectangle(0,0,20.4,14.3), null);


(lib.carrot01_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF3300").s().p("AhFAmIgFgLIAAgIQgBgRACgHIABgDQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBAAAAABIAAAVIACALIADAFQABAFgDABIgCAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAgAgUAPQgFgMAAgEQgBgGABgNIABgDIADABIABADIAAAJQAAALAGALIACACQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgCAAgCgFgAATANIgCgDQgDgKAAgTQAAgIACgDQACgFACACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIgBAEIgBAJQABARADAGIABAFQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIAAAAIgDgCgABEAIQgFgJgBgHQgBgEAAgNQABgKADgEQABAAAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABABgBAEQgDAEABAJQABAQAGAJIACAEQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgBAAQgCAAgCgEg");
	this.shape.setTransform(16.0833,4.2225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AATA5QgaAAgTgDIgagEQgjgFgKgCQgZgGgOgPQgFgGACgDQABgCADgBQApgSAqgPIgBADQgCAIABAQIAAAIIAFALQACADADgBQADgBgBgFIgDgFIgCgLIAAgVQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAQAagJAagIIAagHQAWgFAtgDIAhAAQAEAAABACIAAAAQAAAAABAAQABgBAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAgBABIgBADQgBACgBAHIgBAMIAAAGIgCANIgBASIABAUIAAABIgBAOIAAAAIgHABQgKAAgQADIgZAGQgOACgZAAIgRAAgAgEgmIgBADQgBANABAGQAAAFAFALQABAFACAAQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAAAIgCgCQgFgLAAgMIAAgJIgBgDIgCgBIgBAAgAAkgtQgCADAAAIQAAAUADAKIACADQAAABABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBIgBgFQgDgGgBgSIABgJIABgEQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAgBAAIgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAQgBABAAABgABVg2QgDAEgBAKQAAANABAEQABAHAFAKQADAFACgBQABAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBIgCgEQgGgKgBgQQgBgJADgEQABgEgBgBIgBAAIgDAAg");
	this.shape_1.setTransform(14.0705,5.7042);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot01_mc, new cjs.Rectangle(0,0,28.2,11.4), null);


(lib.Tween7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {mouse:0};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tween9("synched",0);
	this.instance.setTransform(17,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(54));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.9,-35.7,115.9,71.5);


(lib.mouse02_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tween7("synched",0);
	this.instance.setTransform(40.9,35.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mouse02_mc, new cjs.Rectangle(0,0,115.9,71.6), null);


(lib.mouse01_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {"mouse":0};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_53 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(53).call(this.frame_53).wait(1));

	// Layer_1
	this.mouse02_mc = new lib.mouse02_mc();
	this.mouse02_mc.name = "mouse02_mc";
	this.mouse02_mc.setTransform(74.9,35.8,1,1,0,0,0,57.9,35.8);

	this.instance = new lib.Tween8("synched",0);
	this.instance.setTransform(1984.35,35.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.mouse02_mc}]}).to({state:[{t:this.instance}]},53).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.mouse02_mc).to({_off:true,regX:0,regY:0,x:1984.35,y:35.75,mode:"synched",startPosition:0},53).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(17,0,2025.3,71.6);


// stage content:
(lib.Carrots = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		this.stop();
		
		this.horay_mc.visible = false;
		this.reply_btn.visible = false;
		
		var keepcount = 0;
		
		this.carrot01_mc.addEventListener("click", addOne.bind(this));
		this.carrot02_mc.addEventListener("click", addOne.bind(this));
		this.carrot03_mc.addEventListener("click", addOne.bind(this));
		this.carrot04_mc.addEventListener("click", addOne.bind(this));
		this.carrot05_mc.addEventListener("click", addOne.bind(this));
		function addOne(e) {
			e.currentTarget.visible = false;
			if (keepcount == 4){
				this.horay_mc.visible = true;
				this.reply_btn.visible = true;
				
			}else {
				keepcount++;
			}
			
			
			this.showscore.text = keepcount;	
				
		}
		
		
		this.reply_btn.addEventListener("click", refreshPage.bind(this));
		
		function refreshPage(){
			location.reload();
			return false;
		}
		
		
		this.stage.cursor = "none";
		this.cursor_mc.mouseEnabled = false;
		this.addEventListener("tick", CustomMouseCursor.bind(this));
		
		function CustomMouseCursor() {
			this.cursor_mc.x = stage.mouseX / stage.scaleX;
			this.cursor_mc.y = stage.mouseY / stage.scaleY;
		}
		
		
		var _this = this;
		
		_this.play_btn.on('click', function(){
			
			if (_this.song)
				_this.song.play();
			else
				_this.song = createjs.Sound.play("song");
		});
		
		this.stop_btn.on("click", function()
		{
			if (_this.song){
				_this.song.stop();
				_this.song = null;
			}		
		});
		
		this.pause_btn.on("click", function(){
			if (_this.song)
				_this.song.paused = true;		
		});
		
		
		this.mouse01_mc.stop();
		
		this.mouse01_mc.addEventListener("click", playdog.bind(this));
		
		function playdog(){
			this.mouse01_mc.play();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer_17
	this.cursor_mc = new lib.cursor_mc();
	this.cursor_mc.name = "cursor_mc";
	this.cursor_mc.setTransform(1804.95,181.95);

	this.timeline.addTween(cjs.Tween.get(this.cursor_mc).wait(1));

	// reply
	this.reply_btn = new lib.reply_btn();
	this.reply_btn.name = "reply_btn";
	this.reply_btn.setTransform(1431.7,930.65,1,1,0,0,0,95.8,86.7);
	new cjs.ButtonHelper(this.reply_btn, 0, 1, 2, false, new lib.reply_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.reply_btn).wait(1));

	// yay
	this.horay_mc = new lib.horay_mc();
	this.horay_mc.name = "horay_mc";
	this.horay_mc.setTransform(969.9,526.4,1,1,0,0,0,992.3,548.8);

	this.timeline.addTween(cjs.Tween.get(this.horay_mc).wait(1));

	// mouse
	this.mouse01_mc = new lib.mouse01_mc();
	this.mouse01_mc.name = "mouse01_mc";
	this.mouse01_mc.setTransform(126.45,990.6,1,1,0,0,0,57.9,35.8);

	this.timeline.addTween(cjs.Tween.get(this.mouse01_mc).wait(1));

	// bunny
	this.instance = new lib.bunny();
	this.instance.setTransform(1527,561,0.2465,0.2465);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// carrot_1
	this.pause_btn = new lib.pause_btn();
	this.pause_btn.name = "pause_btn";
	this.pause_btn.setTransform(1497.8,55.7,1,1,0,0,0,21.6,30.7);
	new cjs.ButtonHelper(this.pause_btn, 0, 1, 1);

	this.stop_btn = new lib.stop_btn();
	this.stop_btn.name = "stop_btn";
	this.stop_btn.setTransform(1573.3,54.5,1,1,0,0,0,28.4,26.8);
	new cjs.ButtonHelper(this.stop_btn, 0, 1, 1);

	this.play_btn = new lib.play_btn();
	this.play_btn.name = "play_btn";
	this.play_btn.setTransform(1641.8,54.4,1,1,0,0,0,21.4,24.4);
	new cjs.ButtonHelper(this.play_btn, 0, 1, 1);

	this.carrot03_mc = new lib.carrot03_mc();
	this.carrot03_mc.name = "carrot03_mc";
	this.carrot03_mc.setTransform(1159,746.85,1,1,0,0,0,11.2,6.8);

	this.showscore = new cjs.Text("", "40px 'MV Boli'", "#7D016E");
	this.showscore.name = "showscore";
	this.showscore.lineHeight = 66;
	this.showscore.lineWidth = 68;
	this.showscore.parent = this;
	this.showscore.setTransform(587.2,61.65);

	this.carrot05_mc = new lib.carrot05_mc();
	this.carrot05_mc.name = "carrot05_mc";
	this.carrot05_mc.setTransform(424.35,277.5,1.378,1.378,0,0,0,25.4,6.4);

	this.carrot04_mc = new lib.carrot04_mc();
	this.carrot04_mc.name = "carrot04_mc";
	this.carrot04_mc.setTransform(499.25,978.65,1.7175,1.7175,0,0,0,11.2,7.4);

	this.carrot02_mc = new lib.carrot02_mc();
	this.carrot02_mc.name = "carrot02_mc";
	this.carrot02_mc.setTransform(1832.6,821.85,1,1,0,0,0,10.2,7.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#573385").s().p("AM9OJQgWgDgLgIQgJgGgIgOQgHgNgKgYQgFgMgCgKQgBgIABgQQADggAIgaQAIgbAMgKQAKgJASgFQAKgEAJAAQAIABAPAFIA1ASQASAGAFAIQACADADAQQAEARAOAXIAcAsQAHAKAGADQAFACAMgBQARgBAOADQAQADAIAIQAFAHAAAJQAAAJgFAIQgIAOgUAEQgHACgKABIgRAAQgYgBgLgFQgKgEgQgMQgSgRAAgOQgHABgCAPQgCANgKALQgKAKgNAEQgNAFgTAAIgWgBgANGLWQgOALgEAQQgCAJgBASQgEARABAEQABAJAKAQIAFAMQAEAGAEACQAEABANgEIAOgCQAIgCAEgEQACgEAAgLQgBgaACgIQADgIgBgDIgEgMQgEgJADgVQABgIgCgDQgDgFgJgBIgCAAQgPAAgNAKgAH3OIQhQAAg1gQQhUgag4hDIgOgTQgPgDgLgJQgMgLgLgdQgOgngDgSQgDgVACgaIAFgwQADgZAEgNQADgLAMgZIAshWQALgWAJgGQAKgGAWgGQAHgDAMgJQANgJAHgDQAPgGAXABIAYABQAQgFAQAAQAYAAApAKQBDAUAiAcQASAPAeAlQAJAMACAFQADANgIAHQgKAIgVgOIg0gjQgegUgZgIQgcgKgmgDQgegDgSAHQgNAFgWATQgiAbgMAWQgMAUgFAhQgCATgDAnIgDAcQgBAQAAAMQACAkAWAiQAVAfAhAVQA3AiBZAFQAoACAagIQAKgDAQgIIAZgLQAggMAWAKQARAIAGATQAHATgJAQQgKAUgmAQQghAPgQAEQgbAIgrAAIgKAAgEAgvAN1QgMgCgggJQgogMgPgQQgNgOgCgTQgDgXAPgOQAHgHALgCQALgBAIAFQAHAFAKAMQAHAFAMAEQAVAHAJAAQAMABAWgIQAagKAGgLQAHgOgHgQQgFgMgPgMQgUgRgcgMQgXgHgMgFQgkgQgVghQgMgTgBgQQgBgXAUgaQARgVAUgMQAWgOAXACQAUAAAbAOQARAKAIAJQAMAQgDAOQgCAIgHAGQgGAFgIAAQgGgBgGgDIgLgHQgOgGgQADQgQAEgJAMQgEAFAAAEQAAAEAGAHQAKAIAaAHQAtAOAdAUQAlAcALAlQAFARAAAhQAAAggIAPQgEAJgQAQQgVAUgOAIQgaAPgfAAIgUgBgAYbNmQgfgBgPgGQgPgFgRgPQgWgUgMgSQgPgZgFgkQgDgVgBgtQAAgbAEgKQAFgRATgSQAggdAogLQAZgGAggBQAjgBATAJQARAHAPAQQAJAKAPAWQAKAPAEAKIAGAZIAKAiQAGAVgEAbQgHArgcAfQgdAggqAIQgOACgZAAIgSAAgAYpJvQgPABghAKQgaAJgIAMQgGAKgBATQgDAuAQArQAEANAIAFQAGAEAPAAQAqgBAVgFQAkgKARgYQAJgMABgOQAAgGgCgIIgEgOQgHgYgEgLQgHgUgMgKQgRgOgZAAIgFABgAUKNPQgFgGgHgSIgahHQgGgQgCgIIgBgYQgFgdABgPQABgMAGgKQAHgKALgCQAGgBAMAAQAKgBAOgIIAXgOQAYgLAbAIQAKACAFAHQAEAGAAAJQAAAXgYATIgVAOIgUAOQgIAGgCAFQgCAHAEAJIAIAQIAFAUIAJAVQAEAJADALQAGAegLAQQgKAPgTACIgDAAQgRAAgLgNgARZNRQgPgIgIgSQgFgLgFgXIgHgeQgGgZgBgNIADg1QACgdALgJQAHgGAJAAQAKAAAGAGQAEAEADAAQADAAADgEQALgNARgGQARgHAQACQAYACADAQQACAHgHANIgKARQgHAJgNANIgUAVQgGAHgBAFIAAALIAFAZIAIAUIAIAWQADALgBALQAAAKgHAKQgGAJgJAFQgKAFgLAAQgLAAgJgGgAcoNFQgNgHgIgOQgKgRgDgnIgJhaQgQgCgKgKQgLgJgBgQQgBgPAJgLQAIgJAPgEIgDgbQgFgdAGgMQAFgMAMgGQAMgGAMAFQANAGAKAXQAIAVAGAkIArACQAWABAJAFQAIAEAEAIQAEAIgDAHQgDAJgLAFQgHACgQACQgJACggAJIALBWQABANABAFIAHAaQAEASgHAOQgIARgQAFIgJABQgJAAgKgFgA3LgEQgegUgHg3QgDhHgDgkQgGg+gXgkQgQgBgPAKQgOAKgHAQQgKAZADApQADApAKArIAGAXQACAOAAAKQgCAegUAKQgLAGgNgCQgNgDgKgIQgQgNgKgdQgKgegDgoQgCgZABguQACg6AKgbQANgkAdgXQAmgeA3gGQAogEAXAOQAUAMAQAdQAWApAMBHIAVB2IAHAeQADARgCANQgGAcgeANQgOAEgMAAQgPAAgNgIgA9FgJQgYgHgJgUQgIgPABgWIAFgmQAIguAAhPQABhcADghQADgmAQgQQANgNAVACQAVACALAPQAKAOACAiQAGCAAAB3QAAAkgHAWQgIAegWANQgMAHgOAAQgIAAgJgDgAulgPQgzgFgqgWQgugYgWgoQgOAdgaATQgaAVgfAFQggAFgfgMQgfgMgTgZQgRgXgEggQgFgdAHgfQAIgqAnhDQAPgbAPgLQAUgQAgABQAVAAAlAJIAIi4QAChngChSQgBgqAVgHQAIgCAJAEQAJAEAFAIQAIAMADAWQAHAyABBAQABAmgBBMIgCCrQgBAyAEAYQAJAyAeAqQAcAlAhADQAIABASgCQASgDAJACQAOACAMAKQAMAKAEAPQAEAOgGAPQgGAOgNAIQgOAJgXAAIgNgBgAyrk5QgOADgIAGQgIAHgHARQgNAggJAdQgKAhAAASQgBAdARAUQALANASAEQATAEAPgHQASgIANgUQAJgOAJgZQAFgPgBgIQAAgFgGgPQgFgRACgdQACgigCgMQgSgIgSAAQgJAAgJACgEgiWgAWQgMgGgIgKQgIgLgDgRQgCgLAAgVQAAi/ACkNIABiIQgFgIgBgIQAAgKAGgKIABgCQABgWAGgMQAFgNALgKQALgKANgBQAPgBANAKQANAJAGAPIACAFICPgUQAcgEAPABQAYAAARAIQAVAJAJAVQAKAWgMARQgMAUgtAFIh4AMQgrADgWABIgGAAIABCAIAGgBQAKgCAVAAQAngCAsgFIAlgEQAUgBAQAEQASAGAMAOQANAQgDASQgDATgUANQgOAJgZAFQgxAKhXgDQgUgBgOgDIACFWQAAAVgBAKQgCARgHALQgHAMgLAHQgLAIgNABIgFAAQgLAAgKgEgAF8geQgdgKgagXQg7gygEg+QAAgLABgSIACgeIAAgbQgBgRACgLQACgKAHgQIAJgbIAGgcQAEgQAHgJQAGgJAMgIIAVgPIASgOQAKgJAIgEQAOgHAegCQApgDAMATQAGAIAAAUQACAhgCATQgCAcgIAWQgPAlgkAcQgdAWgtARQgEAcAPAYQAKARAgAXQALAIAGAAQAJABAOgKIA3goQAegUASADQAOADAJAMQAIAMAAAPQAAAagZAXQgIAIgOAJIgYAPIgcARQgRAJgOAEQgLACgMAAQgTAAgTgGgAFylnQgHAFgCAGIAAANQABAJgFALIgIASQAJAAAPgMQAOgLAFgFQAHgKAEgPQAGgWgCgSgAkbgyQgngUgNgnQgEgNgCgbQgFhYALhgIAEgeQgrAFgTgXQgLgNADgTQACgSANgLQAPgLAggCIAIAAQAAgkAFg5QACgUAEgHQAIgQAOACQALABAHANQADAIABAQIAHBbIAPgBIAXAAQAMAAAKAEQALAFAGALQAHAKgEALQgFAPgeALIgoAOIADBsQADBBAFAtQACAXAJAJQAOAPAigKIAZgHQAOgDAKAEQANAFAHANQAHANgCAOQgEAbgcAPQgVALggAAIgFAAQgqAAgfgRgACzgpQgQgBgNgLQgMgLgEgPQgDgJABgNIABgXQAAgRgDgaQgHgwgOgxQgOgvgRgZQgSgdgXgDQgOgBgXAJQgPAGgGAHQgGAFgFAMIABAHIAKBEIACAoQABAaACAPIAHApQADAXgEARQgEAWgQAOQgSAPgTgFQgVgGgJgXQgGgMgDgfIgSjWQgCgpAAhTQgBh8ABg+QAChnAGhSQACgXAEgNQAFgTALgMQAGgGAIgDQAIgCAHAEQAIAFACAUIAGBJIAMC6QAGBogBBSIAAAHQAmgWAtgFQAcgCATAGQAMAFAMAKIAVAUQAWAXAIAOQAQAYAOAtQAcBUAFA0IACA3QAAAggGAOQgHAOgOAIQgNAHgOAAIgDAAgA8LnxQgYgCgRgOQgOgLgHgRQgIgQAAgSQABgXAOgUQAOgSAWgIQAXgIAWAFQAWAGAPASQAQASADAWQADAXgLAVQgKAVgUAMQgRAJgUAAIgHAAg");
	this.shape.setTransform(307.7481,139.4465);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7D016E").s().p("AgEABIACgBIACgBIACAAIAAgBIADABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgCAAIgCABIgBABIgCABg");
	this.shape_1.setTransform(1092.2781,760.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.carrot02_mc},{t:this.carrot04_mc},{t:this.carrot05_mc},{t:this.showscore},{t:this.carrot03_mc},{t:this.play_btn},{t:this.stop_btn},{t:this.pause_btn}]}).wait(1));

	// MergedLayer_5
	this.carrot01_mc = new lib.carrot01_mc();
	this.carrot01_mc.name = "carrot01_mc";
	this.carrot01_mc.setTransform(1607.8,481.05,1,1,0,0,0,14.1,5.7);

	this.instance_1 = new lib.flower2();
	this.instance_1.setTransform(263,541,0.3291,0.3291);

	this.instance_2 = new lib.bookshelf();
	this.instance_2.setTransform(141,283,0.2448,0.2448);

	this.instance_3 = new lib.flower();
	this.instance_3.setTransform(1730,687,0.3261,0.3261);

	this.instance_4 = new lib.lamp();
	this.instance_4.setTransform(835,491,0.2412,0.2412);

	this.instance_5 = new lib.CachedBmp_3();
	this.instance_5.setTransform(1993.3,399.6,0.5,0.5);

	this.instance_6 = new lib.frame();
	this.instance_6.setTransform(931,171,0.2483,0.2483);

	this.instance_7 = new lib.rug();
	this.instance_7.setTransform(480,847,0.2547,0.2547);

	this.instance_8 = new lib.window();
	this.instance_8.setTransform(1291,127,0.3177,0.3177);

	this.instance_9 = new lib.Layer1();
	this.instance_9.setTransform(979,563,0.3081,0.3081);

	this.instance_10 = new lib.CachedBmp_2();
	this.instance_10.setTransform(1087.85,711.85,0.5,0.5);

	this.instance_11 = new lib.baxkground();
	this.instance_11.setTransform(0,-192,0.3258,0.3258);

	this.instance_12 = new lib.CachedBmp_1();
	this.instance_12.setTransform(1061.15,381.2,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.carrot01_mc}]}).wait(1));

	// Layer_1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#02AF00").s().p("AiLG+QgQgBgGgLQAcgSA0gbIBQgsQBfg4BOhRQBOhRA1hiQBMiKgCiBQgBhFgegkQgbgeg5gPQhHgThNAGQhLAGhGAbQiGA0hrB4QhWBhgPBcQgKA3ASA0QASA3ArAfQAbAUAyAQQBGAWAMAFQAKAEAAAGQAAAFgHACQgGACgGgCQhJgQgogQQg8gYgjgmQgmgqgMg+QgKg6AQg6QAbhkBhhiQByhzCHgyQBIgbBKgGQBOgFBIARQBWAXAkAyQAgAsAABQQABChhtCrQhMB3hrBYQhuBbh/AuQgNAFgMAAIgDAAg");
	this.shape_2.setTransform(1128.4921,724.4664);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(937.1,348,1062.6999999999998,828.4000000000001);
// library properties:
lib.properties = {
	id: 'C67BF09CAA0BC74CA9115EC62F0F8228',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/baxkground.jpg?1682133854594", id:"baxkground"},
		{src:"images/bookshelf.jpg?1682133854594", id:"bookshelf"},
		{src:"images/rug.png?1682133854594", id:"rug"},
		{src:"images/Carrots_atlas_1.png?1682133854554", id:"Carrots_atlas_1"},
		{src:"images/Carrots_atlas_2.png?1682133854554", id:"Carrots_atlas_2"},
		{src:"images/Carrots_atlas_3.png?1682133854554", id:"Carrots_atlas_3"},
		{src:"images/Carrots_atlas_4.png?1682133854555", id:"Carrots_atlas_4"},
		{src:"sounds/song.mp3?1682133854594", id:"song"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C67BF09CAA0BC74CA9115EC62F0F8228'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;